# Generated by Django 4.0.6 on 2022-07-22 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ingrese el nombre del género (p. ej. Ciencia Ficción, Terror etc.)', max_length=200)),
            ],
        ),
    ]
