# Generated by Django 4.0.6 on 2022-07-22 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0002_author_movie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='isbn',
        ),
        migrations.AlterField(
            model_name='movie',
            name='sumary',
            field=models.TextField(help_text='Descripcion de la Pelicula', max_length=100),
        ),
    ]
