# Generated by Django 4.0.6 on 2022-07-23 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0004_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='description',
            name='name',
            field=models.TextField(help_text='Descripcion de la pelicula.)', max_length=200),
        ),
    ]
